  # Common configuration ("container" active profile)
server:
  port: 8081

logging:
  level:
    org.art.web: DEBUG

spring:
  # MySQL datasource configuration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
